FROM ubuntu:17.10
LABEL maintainer="Denis Ivanov"

# Quiet apt-get
ARG DEBIAN_FRONTEND=noninteractive

ENV TAG=v0.0.0
ENV BUILD=0

# Project
RUN mkdir -p /srv/

# Install deps
COPY requirements.txt /tmp/
RUN apt-get -y -qq update && \
    apt-get -y -qq install \
        curl \
        gcc \
        libjpeg-dev \
        libpq-dev \
        python3-dev \
        python3-pip \
        zlib1g-dev && \
    pip3 install -r /tmp/requirements.txt

# Cleaning
RUN rm -f /tmp/requirements.txt && \
    apt-get -y -qq autoremove && \
    apt-get -y -qq clean

WORKDIR /srv/

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:8000/healthz || exit 1

ENTRYPOINT [ "python3" ]
CMD [ "/srv/smart_manage.py", "runserver", "0.0.0.0:8000" ]
