FROM tetafro/caddy:latest
LABEL maintainer="Denis Ivanov"

RUN mkdir -p /app/project
COPY deploy/configs/caddy/Caddyfile .

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD nc -z localhost 443 || exit 1
