FROM certbot/certbot
LABEL maintainer="Denis Ivanov"

# Update certificate twice a day
RUN touch crontab.tmp && \
    echo '0 */12 * * * certbot renew --quiet' > crontab.tmp && \
    crontab crontab.tmp && \
    rm -rf crontab.tmp

ENTRYPOINT ["/usr/sbin/crond", "-f", "-d", "0"]
