FROM ubuntu:16.10
MAINTAINER Denis Ivanov

# Quiet apt-get
ARG DEBIAN_FRONTEND=noninteractive

# Server mode
ENV SERVER_MODE=dev

# Install deps
COPY requirements.txt /tmp/
RUN apt-get -y update && \
    apt-get -y install \
        bc \
        curl \
        gcc \
        libjpeg-dev \
        libpq-dev \
        python3-dev \
        python3-pip \
        zlib1g-dev && \
    pip3 install -r /tmp/requirements.txt && \
    curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get -y install nodejs && \
    npm install --silent -g webpack

# Project
RUN mkdir -p /srv/

# Cleaning
RUN rm -f /tmp/requirements.txt && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    npm cache --force clean

WORKDIR /srv/
