FROM nginx:1.13
MAINTAINER Denis Ivanov

RUN mkdir -p /etc/nginx/sites-avaliable
RUN mkdir -p /etc/nginx/sites-enabled
COPY deploy/configs/nginx/nott.conf /etc/nginx/sites-avaliable/
RUN ln -s /etc/nginx/sites-avaliable/nott.conf /etc/nginx/sites-enabled/
COPY deploy/configs/nginx/nginx.conf /etc/nginx/
