FROM ubuntu:16.10
LABEL maintainer="Denis Ivanov"

# Quiet apt-get
ARG DEBIAN_FRONTEND=noninteractive

# Project
RUN mkdir -p /srv/ /srv/public/.well-known
COPY project /srv/
COPY requirements.txt /srv/
COPY deploy/docker/docker-entrypoint.sh /docker-entrypoint.sh

# Install deps
RUN apt-get -y update && \
    apt-get -y install \
        gcc \
        libjpeg-dev \
        libpq-dev \
        python3-dev \
        python3-pip \
        zlib1g-dev && \
    pip3 install -r /srv/requirements.txt && \
    pip3 install gunicorn

# Cleaning
RUN apt-get -y autoremove && \
    apt-get -y clean

WORKDIR /srv/
