FROM ubuntu:16.10
MAINTAINER Denis Ivanov

# Quiet apt-get
ARG DEBIAN_FRONTEND=noninteractive

# Server mode
ENV SERVER_MODE=prod

# Install deps
COPY requirements.txt /tmp/
RUN apt-get -y update && \
    apt-get -y install \
        gcc \
        libjpeg-dev \
        libpq-dev \
        python3-dev \
        python3-pip \
        zlib1g-dev && \
    pip3 install -r /tmp/requirements.txt && \
    pip3 install gunicorn

# Project
COPY install/nott.tar.gz /tmp/
COPY deploy/docker/docker-entrypoint.sh /docker-entrypoint.sh
RUN mkdir -p /srv/ && \
    mkdir -p /srv/logs/ && \
    tar -C /srv -xzf /tmp/nott.tar.gz && \
    mv /srv/nott/* /srv/ && \
    rm -rf /srv/nott/ && \
    mkdir -p /srv/public/.well-known

# Cleaning
RUN rm -f /tmp/requirements.txt && \
    rm -f /tmp/nott.tar.gz && \
    apt-get -y autoremove && \
    apt-get -y clean

WORKDIR /srv/
