FROM tetafro/webpack:8 AS build

WORKDIR /srv/
COPY project/public/js .
RUN npm install --silent && \
    webpack

FROM tetafro/gunicorn:ubuntu-16.10
LABEL maintainer="Denis Ivanov"

ENV TAG=v0.0.0
ENV BUILD=0

# Quiet apt-get
ARG DEBIAN_FRONTEND=noninteractive

# Project
RUN mkdir -p /srv/public/{.well-known,media}
COPY project /srv/
COPY requirements.txt /srv/
COPY deploy/configs/gunicorn/gunicorn.py /srv/
COPY --from=build /srv/app.min.js /srv/public/js/

# Install deps
RUN apt-get -y -qq update && \
    apt-get -y -qq install \
        curl \
        libjpeg-dev \
        libpq-dev \
        zlib1g-dev && \
    pip3 install -r /srv/requirements.txt

# Cleaning
RUN apt-get -y -qq autoremove && \
    apt-get -y -qq clean

WORKDIR /srv/

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:8000/healthz || exit 1

ENTRYPOINT [ "gunicorn" ]
CMD [ "--config", "/srv/gunicorn.py", "core.wsgi:application" ]
