FROM python:3.6
LABEL maintainer="Denis Ivanov"

RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' >> /etc/apt/sources.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get -y -qq update && \
    apt-get -y -qq install postgresql-client-9.6 python3-pip && \
    pip3 install dropbox schedule

COPY scripts/db_backup.py /app/

CMD ["python3", "/app/db_backup.py"]
