# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('datatype', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=80)),
            ],
        ),
    ]
