# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('admin', '0001_initial'), ('admin', '0002_auto_20171204_0812'), ('admin', '0003_auto_20180105_1616')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('datatype', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=80)),
            ],
        ),
    ]
