# Generated by Django 2.0.1 on 2018-01-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0005_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/public/images/no-avatar.png', max_length=200),
        ),
    ]
